In [1]:
import numpy as np
import pandas as pd

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class']
ds = pd.read_csv(url, names=names)

In [3]:
ds.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
#normalization

list_sl=[]
list_sw=[]
list_pl=[]
list_pw=[]
for sl in ds['sepal length']:
    sl = (sl-min(ds['sepal length']))/(max(ds['sepal length'])-min(ds['sepal length']))
    list_sl.append(sl)
for sw in ds['sepal width']:
    sw = (sw-min(ds['sepal width']))/(max(ds['sepal width'])-min(ds['sepal width']))
    list_sw.append(sw)    
for pl in ds['petal length']:
    pl = (pl-min(ds['petal length']))/(max(ds['petal length'])-min(ds['petal length']))
    list_pl.append(pl)
for pw in ds['petal width']:
    pw = (pw-min(ds['petal width']))/(max(ds['petal width'])-min(ds['petal width']))
    list_pw.append(pw) 

X = np.array( list(zip(list_sl,list_sw, list_pl, list_pw)) )  

In [5]:
print (X)

[[ 0.22222222  0.625       0.06779661  0.04166667]
 [ 0.16666667  0.41666667  0.06779661  0.04166667]
 [ 0.11111111  0.5         0.05084746  0.04166667]
 [ 0.08333333  0.45833333  0.08474576  0.04166667]
 [ 0.19444444  0.66666667  0.06779661  0.04166667]
 [ 0.30555556  0.79166667  0.11864407  0.125     ]
 [ 0.08333333  0.58333333  0.06779661  0.08333333]
 [ 0.19444444  0.58333333  0.08474576  0.04166667]
 [ 0.02777778  0.375       0.06779661  0.04166667]
 [ 0.16666667  0.45833333  0.08474576  0.        ]
 [ 0.30555556  0.70833333  0.08474576  0.04166667]
 [ 0.13888889  0.58333333  0.10169492  0.04166667]
 [ 0.13888889  0.41666667  0.06779661  0.        ]
 [ 0.          0.41666667  0.01694915  0.        ]
 [ 0.41666667  0.83333333  0.03389831  0.04166667]
 [ 0.38888889  1.          0.08474576  0.125     ]
 [ 0.30555556  0.79166667  0.05084746  0.125     ]
 [ 0.22222222  0.625       0.06779661  0.08333333]
 [ 0.38888889  0.75        0.11864407  0.08333333]
 [ 0.22222222  0.75        0.08

In [6]:
nc = 3         # number of classes
W = []         # list for w vectors
M = len(X)     # number of x vectors
N = len(X[0])  # dimensionality of x vectors

In [7]:
def get_weights():
    y = np.random.random() * (2.0 / np.sqrt(M))
    return 0.5 - (1 / np.sqrt(M)) + y

In [8]:
for i in range(nc):
    W.append(list())
    for j in range(N):
        W[i].append(get_weights() * 0.5)

In [9]:
def distance(w, x):
    r = 0
    for i in range(len(w)):
        r = r + (w[i] - x[i])*(w[i] - x[i])
    
    r = np.sqrt(r)
    return r

In [10]:
def Findclosest(W, x):
    wm = W[0]
    r = distance(wm, x)
    
    i = 0
    i_n = i
    
    for w in W:
        if distance(w, x) < r:
            r = distance(w, x)
            wm = w
            i_n = i
        i = i + 1
    
    return (wm, i_n)

In [11]:
print(W)

[[0.26248757725969107, 0.2550877752455607, 0.26798881798361374, 0.21424487703069942], [0.25152412185511314, 0.26745894958836658, 0.28950583222420906, 0.24036104366360331], [0.27487658136897475, 0.24233009927819765, 0.27183418337333165, 0.21299801279461131]]


In [12]:
la = 0.3    # λ coefficient
dla = 0.05  # Δλ

while la >= 0:
    for k in range(10):
        for x in X:
            wm = Findclosest(W, x)[0]
            for i in range(len(wm)):
                wm[i] = wm[i] + la * (x[i] - wm[i]) 

    la = la - dla 

In [13]:
Data = list() 

for i in range(len(W)):
    Data.append(list())

dfList = ds['class'].as_matrix()

In [14]:
DS = list()
i = 0
for x in X:
    i_n = Findclosest(W, x)[1]
    Data[i_n].append(x)
    DS.append([i_n, dfList[i]])
    i = i + 1

print (DS) 

[[0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'], [0, 'Iris-setosa'],